# Generated by Django 5.1.4 on 2024-12-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bigmenu',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='bigmenu',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='smallmenu',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='smallmenu',
            old_name='name',
            new_name='title',
        ),
    ]
